#!/bin/bash -e

: ${STORAGE_ACCOUNTS:=5}
: ${NAME_PREFIX:=dash}
: ${LOCATION:="West Europe"}
: ${CSCONFIG_FILE:="ServiceConfiguration.Cloud.cscfg"}
: ${AZURE_CLI_LOCATION:="/azure"}

azure(){
  "$AZURE_CLI_LOCATION"/bin/azure "$@"
}

set_params() {
  if [ $# -ne 0 ]; then
    if [ $# -eq 2 ] || [ $# -eq 4 ] || [ $# -eq 6 ]; then
      for ((i_flag=1;i_flag<=$#;i_flag=i_flag+2)); do
        case "${!i_flag}" in
          --prefix)
            local i_value=$((i_flag+1))
            NAME_PREFIX="${!i_value}"
            ;;
          --accounts)
            local i_value=$((i_flag+1))
            STORAGE_ACCOUNTS="${!i_value}"
            local re='^[0-9]+$'
            if ! [[ $STORAGE_ACCOUNTS =~ $re ]]; then
              usage
            fi
            ;;
          --location)
            local i_value=$((i_flag+1))
            LOCATION="${!i_value}"
            local re='^(Central US|South Central US|East US|West US|North Central US|East US 2|North Europe|West Europe|Southeast Asia|East Asia|Japan West|Japan East|Brazil South)$'
            if ! [[ $LOCATION =~ $re ]]; then
              usage
            fi
            ;;
          *)
            usage
            ;;
        esac
      done
    else
      usage
    fi
  fi
}

print_params() {
  echo "Number of storage accounts: $STORAGE_ACCOUNTS"
  echo "Name prefix of accounts and services: $NAME_PREFIX"
  echo "Location of storage accounts and the DASH cloud service: $LOCATION"
}

deploy_dash() {
  azure login
  azure config mode asm

  declare -a account_names

  for ((i=0;i<=STORAGE_ACCOUNTS;i++)); do
    hash=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-z0-9'| fold -w 16 | head -n 1)
    account_name="$NAME_PREFIX$i$hash"
    account_names[$i]=$account_name
    azure storage account create -l "$LOCATION" --type LRS "$account_name"
  done

  write_first_part

  hash=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-z0-9'| fold -w 16 | head -n 1)
  dash_account_name="${NAME_PREFIX}${hash}"
  dash_account_key=$(head -c 64 /dev/urandom | base64)
  echo '      <Setting name="AccountName" value="'"$dash_account_name"'" />' >> $CSCONFIG_FILE
  echo '      <Setting name="AccountKey" value="'"$dash_account_key"'" />' >> $CSCONFIG_FILE
  echo '      <Setting name="SecondaryAccountKey" value="" />' >> $CSCONFIG_FILE

  declare -i i=0
  for account_name in ${account_names[@]}; do
    account_key=$(azure storage account keys list --json "$account_name" | jq -r .primaryKey)
    [[ $i -eq 0 ]] && setting_name="StorageConnectionStringMaster" || setting_name="ScaleoutStorage$((i-1))"
    storage_setting='      <Setting name="'"$setting_name"'" value="DefaultEndpointsProtocol=https;AccountName='$account_name';AccountKey='"$account_key"'" />'
    echo "$storage_setting" >> $CSCONFIG_FILE
    ((i++))
  done

  for ((i=STORAGE_ACCOUNTS;i<=15;i++)); do
    echo '      <Setting name="ScaleoutStorage'$i'" value="" />' >> $CSCONFIG_FILE
  done

  write_final_part

  create_cloud_service $dash_account_name

  print_info $dash_account_name $dash_account_key $account_names
}

write_first_part() {
  # TODO: Instances count??
  cat>$CSCONFIG_FILE<<EOF
<?xml version="1.0" encoding="utf-8"?>
<ServiceConfiguration serviceName="DashServer.Azure" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceConfiguration" osFamily="4" osVersion="*" schemaVersion="2014-06.2.4">
  <Role name="DashServer">
    <Instances count="1" />
    <ConfigurationSettings>
      <Setting name="Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString" value="" />
EOF
}

write_final_part() {
  cat>>$CSCONFIG_FILE<<EOF
      <Setting name="LogNormalOperations" value="true" />
      <Setting name="ReplicationPathPattern" value="" />
      <Setting name="ReplicationMetadataName" value="" />
      <Setting name="ReplicationMetadataValue" value="" />
      <Setting name="WorkerQueueName" value="" />
      <Setting name="AsyncWorkerTimeout" value="" />
      <Setting name="WorkerQueueInitialDelay" value="" />
      <Setting name="WorkerQueueDequeueLimit" value="" />
    </ConfigurationSettings>
    <Certificates></Certificates>
  </Role>
</ServiceConfiguration>
EOF
}

create_cloud_service() {
  echo "creating cloud service $1"
  azure service create --serviceName $1 --description "Created with dash-deployer" --location "$LOCATION"
  azure service deploy --packageUrl "https://hwxdash.blob.core.windows.net/v04/DashServer.Azure.cspkg" --configFile ./ServiceConfiguration.Cloud.cscfg --cloudService $1 --deploymentLabel $1 -d production
}

print_info() {
  echo -e "\nAzure resources created:\n"
  echo "  Cloud Service:"
  echo "    $1"
  echo -e "  Storage Accounts:"
  for account_name in ${account_names[@]}; do
    echo -e "    $account_name"
  done
  echo -e "\nDASH service details:\n"
  echo -e "  AccountName = $1"
  echo -e "  AccountKey = $2\n"
}

usage() {
  echo -e "Deploy DASH to an Azure cloud service and create its storage accounts\n"
  echo -e "usage: deploy-dash [options]\n"
  echo "Options:"
  echo "  --accounts     number of scaleout storage accounts"
  echo "  --prefix       name prefix of Azure resources"
  echo "  --location     Azure region [Central US, South Central US, East US, West US, North Central US, East US 2, North Europe, West Europe, Southeast Asia, East Asia, Japan West, Japan East, Brazil South]"
  exit 1
}

main() {
  set_params "$@"
  print_params
  deploy_dash
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"